### PR TITLE
Uri handler multiple windows

### LINKED ISSUE #151: Auth flow does not specify which project to open vscode:// link in
When using the auth flow the vscode:// link will open in the active VSCode window. There is a potential for the wrong window to be in context when the data for auth is returned, resulting in creating a config in the wrong project.

- Look into a way we can open the window that initiated the auth flow

/cc @anthmatic

### PR DESCRIPTION
**Pull request by miketalley**
Fixes #151 

Related Info
https://code.visualstudio.com/api/references/vscode-api#window.registerUriHandler

### CODE REVIEW

**Comment by anthmatic** [comment]
Testing this locally (with the PAKUI changes locally) it still just seems to open the most recent window, not the originating window. Am I missing a step?

File: src/lib/commands/auth.ts [hunk 1]
```diff
@@ -1,11 +1,13 @@
...
-export const registerCommands = (context: ExtensionContext) => {
+export const registerCommands = (
+  context: ExtensionContext,
+  rootPath: string
+) => {
   context.subscriptions.push(
     commands.registerCommand(COMMANDS.AUTHORIZE_ACCOUNT, async () => {
-      const authUrl =
-        'https://app.hubspot.com/l/personal-access-key/auth/vscode';
+      const authUrl = `https://app.hubspot.com/l/personal-access-key/auth/vscode${rootPath}`;
```
Comment (anthmatic) [inline src/lib/commands/auth.ts:10]: I can't fully test the flow on Windows but since `rootPath` uses `fsPath`, this path contains the windows style path which looks like `.../auth/vscodec:\folder` which causes a 404

**Review by anthmatic — APPROVED** [review]
Can't fully test the Windows stuff yet but LGTM otherwise

File: src/lib/commands/auth.ts (hunk 1 above)
Comment (miketalley) [reply src/lib/commands/auth.ts:10]: Switched to using `path` instead of `fsPath` and also added a fix for the value of `rootPath` that is returned from personal-access-key-ui, which is something like `/C:/Folder`. The fix slices off the leading `/`.

Let me know if you see any issues with this.
